jobs:
# It'll be displayed in the Fivetran dashboard once your jobs are imported.
# Job names must be unique.
 - name: dag1
   schedule: 15 1-21 * * 1-5 #
   steps:
     - name: run_all_models
       command: dbt run
     - name: test_all_models
       command: dbt test
     #- name: run_rpt_models
     #  command: dbt run --select models/rpt/ 
     #- name: test_rpt_models
     #  command: dbt test --select models/rpt/
