# Fivetran jobs definition to schedule Data  pipelines based on DBT
jobs:
 - name: dag1
   schedule: 15 6-20 * * 1-5 # At minute 15 past every hour every day-of-week from Monday through Friday 
   steps:
     - name: run_all_models
       command: dbt run
     - name: test_all_models
       command: dbt test

