---
version: 2.1
parameters:
  is-my-workflow:
    type: boolean
    #type: string #enum
    #type: enum
    #enum:
    #  - w1
    #  - w2
    default: false  #w1 #"datacalc"
jobs:
  build-and-test:
    docker:
      - image: busybox
    steps:
      - run: echo "GWIM workflow => << pipeline.parameters.is-my-workflow >>"
      - when:
          condition: << pipeline.parameters.is-my-workflow >>
          steps:
            - run: echo "It's mine"
            - run: echo "Bye!"
      - unless:
          condition: << pipeline.parameters.is-my-workflow >>
          steps:
            - run: echo "It's not mine"
            - run: echo "Bye ..."       
workflows:
  sample:
    jobs:
      - build-and-test
