---
version: 2.1
parameters:
  is-gwim-workflow:
    type: boolean
    #type: string #enum
    #type: enum
    #enum:
    #  - w1
    #  - w2
    default: false  #w1 #"datacalc"
jobs:
  build-and-test:
    docker:
      - image: busybox
    steps:
      - run: echo "Is it GIWM workflow  << pipeline.parameters.is-gwim-workflow >>"
      - run:
          name: Run tests
          command: echo "<< pipeline.parameters.is-gwim-workflow >>"
workflows:
  sample:
    jobs:
      - build-and-test
