---
version: 2.1
parameters:
  workflow:
    type: string #enum
    #enum:
    #  - w1
    #  - w2
    default: "datacalc"
jobs:
  build-and-test:
    docker:
      - image: busybox
    steps:
      - run:
          name: Run tests
          command: echo "Parameter workflow: << pipeline.parameters.workflow >>"
workflows:
  sample:
    jobs:
      - build-and-test
